version: "3"

services:
  rl-donkeycar:
    build:
      context: .
      dockerfile: Dockerfile-DDQN
    image: rl-donkeycar
    ports:
      - "6006:6006"
    volumes:
      - ./gym-donkeycar/examples/reinforcement_learning:/app/examples/reinforcement_learning
    extra_hosts:
      - "host.docker.internal:host-gateway"