FROM python:3.9

RUN pip install tensorboard==2.12.2
RUN pip install gym==0.21 pillow==9.5.0 stable-baselines3==1.8.0 pyglet==1.5.27 numpy==1.22.3 torch==1.11.0

WORKDIR /app

COPY gym-donkeycar /app
RUN pip install .

EXPOSE 6006

CMD ["tensorboard", "--logdir", "examples/reinforcement_learning/ppo_donkeycar_tensorboard", "--port", "6006", "--host", "0.0.0.0"]