FROM python:3.7

RUN pip install tensorflow==1.13.1
RUN pip install tensorboard==1.15.0
RUN pip install gym==0.21 pillow==9.5.0 stable-baselines3==1.8.0 torch==1.11.0 pyglet==1.5.27 h5py==2.8.0 opencv-python==3.4.2.17
RUN pip install protobuf==3.20.0

WORKDIR /app

COPY donkeycar /app
RUN pip install git+https://github.com/tawnkramer/gym-donkeycar

EXPOSE 6006

CMD ["tensorboard", "--logdir", "./ddqn_donkeycar_tensorboard/", "--port", "6006", "--host", "0.0.0.0"]